[tool.black]
line-length = 88

[tool.ruff]
line-length = 88
target-version = "py313"
select = ["F", "E"]
ignore = ["W"]
fix = true

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
